<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>sgbono_windows_update</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>AnyCPU</PlatformTarget>
	<LangVersion>10</LangVersion>
	<ApplicationManifest>app.manifest</ApplicationManifest>
	<ApplicationIcon>windows-update-icon-9-1671344843.ico</ApplicationIcon>
	<AssemblyName>GWXI</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PreferNativeArm64>True</PreferNativeArm64>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PreferNativeArm64>True</PreferNativeArm64>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="windows-update-icon-9-1671344843.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.9.30" />
  </ItemGroup>

</Project>
